### ISSUE TITLE
[Node.js] Unable to build using the amalgamation

### ISSUE THREAD

**Issue by m4heshd** [utelle/SQLite3MultipleCiphers#42] opened 2021-07-22 09:30 UTC
I'm trying to build [`better-sqlite3`](https://github.com/JoshuaWise/better-sqlite3) with the latest amalgamation but always ends up with this error no matter what version of `sqlitemc` I use.

```shell
sqlite3.c(112699): error C2039: 'nTableLock': is not a member of 'Parse'
sqlite3.c(19096): note: see declaration of 'Parse'
```

Checked the source. `nTableLock` is defined. Error can be reproduced using:

```shell
npm install https://github.com/m4heshd/better-sqlite3-multiple-ciphers-test
```

I've been using `sqleet` amalgamation till now and it works perfectly fine ([`better-sqleet`](https://github.com/m4heshd/better-sqleet)). But I'm trying to upgrade to the latest release of SQLite3. You can also test the successful build with following command. It uses the same version of `better-sqlite3`.

```shell
npm install https://github.com/m4heshd/better-sqlite3-multiple-ciphers-test#sqleet
```

Also tried merging all the compile-time options but no difference. What's going on here?. `Sqlitemc` amalgamation should be a drop-in replacement to the vanilla amalgamation right? So in theory shouldn't this work? 🤔

**Comment by utelle** [comment] 2021-07-22 11:47
> I'm trying to build [`better-sqlite3`](https://github.com/JoshuaWise/better-sqlite3) with the latest amalgamation but always ends up with this error no matter what version of `sqlitemc` I use.
> 
> ```shell
> sqlite3.c(112699): error C2039: 'nTableLock': is not a member of 'Parse'
> sqlite3.c(19096): note: see declaration of 'Parse'
> ```

In fact, the error is provoked by a glitch in the SQLite3 source code. It has nothing to do with the encryption extension. You would get the very same issue, if you compile the original SQLite3 (or sqleet) source code with the preprocessor symbols `SQLITE_OMIT_SHARED_CACHE` and `SQLITE_USER_AUTHENTICATION` both defined.

> Checked the source. `nTableLock` is defined.

No, `nTableLock` is **not** defined, because your compilation step defines the preprocessor symbol `SQLITE_OMIT_SHARED_CACHE`.

The problem is that **SQLite3 Multiple Ciphers** defines the preprocessor symbol `SQLITE_USER_AUTHENTICATION=1`, if the symbol is not already defined. And if the symbol has a non-zero value, then line 112699 (which references `nTableLock`) will be compiled, because it is not checked whether the symbol `SQLITE_OMIT_SHARED_CACHE` is defined (and hence `nTableLock` is **not** defined), and due to the fact that `SQLITE_OMIT_SHARED_CACHE` **is** defined in your case, the compiler emits the error message.

I will report this to the SQLite developer team, so that this will be corrected in the next SQLite version.

For the time being you have 2 options to avoid the problem:

1. Explicitly define symbol `SQLITE_USER_AUTHENTICATION=0`, or
2. Do **not** define symbol `SQLITE_OMIT_SHARED_CACHE`

> I've been using `sqleet` amalgamation till now and it works perfectly fine ([`better-sqleet`](https://github.com/m4heshd/better-sqleet)).

This only works, because **sqleet** does not enable user authentication. If you enable user authentication, you would get the very same error.

> Also tried merging all the compile-time options but no difference. What's going on here?

I hope my above explanations make clear what's going on.

> `Sqlitemc` amalgamation should be a drop-in replacement to the vanilla amalgamation right? So in theory shouldn't this work? 🤔

Yes. And it will, as soon as the problem is fixed in the original SQLite source code.

**Comment by m4heshd** [comment] 2021-07-22 20:53
Thank you so much for the very fast response, taking the time to investigate and in-depth explanation. You've saved me so much time and energy. Setting `SQLITE_USER_AUTHENTICATION=0` does build successfully.

> No, nTableLock is not defined, because your compilation step defines the preprocessor symbol SQLITE_OMIT_SHARED_CACHE.

I didn't know that would completely skip compiling that portion of the source since it's amalgamated. Now that I've read more about it, I seem to have gained a much better understanding on that matter. I think I'm gonna stick with `SQLITE_USER_AUTHENTICATION=0` since I have no use for it and I deal with a lot of multi-threaded usage.

Is there any active issues being tracked about this at SQLite? I'd love to keep an eye on that.

Again, can't thank you enough. On a very tight schedule with my ongoing project and your work is vital to my work. Very thankful that you're actively maintaining this extension.

**Comment by utelle** [comment] 2021-07-23 08:28
Unfortunately, the SQLite developer team does not use a public issue tracker.

I will close this issue when the problem is fixed in the original SQLite source code. Hopefully with the release of the next version.

**Comment by m4heshd** [comment] 2021-07-23 13:58
> I will close this issue when the problem is fixed in the original SQLite source code.

Perfect. Thank you.

**Comment by m4heshd** [comment] 2021-07-24 15:18
Hi @utelle, 

So sorry to keep bothering you but we got error when building on Linux. ☹

```shell
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
Release/obj/gen/sqlite3/sqlite3.c: In function ‘aesGenKeyEncryptInternal’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251971:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 1);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251936:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘_mm_extract_epi32’: target specific option mismatch
 _mm_extract_epi32 (__m128i __X, const int __N)
 ^~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Release/obj/gen/sqlite3/sqlite3.c:251935:0:
/usr/lib/gcc/x86_64-linux-gnu/7/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite3/sqlite3.c:251976:16: note: called from here
         temp = _mm_extract_epi32(_mm_aeskeygenassist_si128(_mm_setr_epi32(0, temp, 0, 0), 0), 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 1
deps/sqlite3.target.mk:195: recipe for target 'Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o' failed
```

Getting this when I ran the build on workflow. Windows is ok. Haven't checked on mac. Vanilla amalgamation builds fine on all.

**Comment by utelle** [comment] 2021-07-24 16:21
On Linux you have to specify the GCC compile time options `-msse4.2 -maes`, so that the code for native AES processor instructions can be compiled correctly.

**Comment by m4heshd** [comment] 2021-07-25 15:09
Perfect. Compiles beautifully on all platforms now. Here's the [final result](https://github.com/m4heshd/better-sqlite3-multiple-ciphers). Just published the package including all the prebuilds. Got this all done with the immense support from you. Thank you so much. I'll be actively maintaining this package consistent to your releases. ☺👏🏻

**Comment by utelle** [comment] 2021-07-25 16:10
> Perfect. Compiles beautifully on all platforms now.

Glad to hear that.

> Here's the [final result](https://github.com/m4heshd/better-sqlite3-multiple-ciphers). Just published the package including all the prebuilds.

Great work. And thanks for mentioning the **SQLite3 Multiple Ciphers** project.

> Got this all done with the immense support from you.

You are welcome. BTW, feedback like yours frequently lead to improvements of the project. 😃 

> Thank you so much. I'll be actively maintaining this package consistent to your releases. ☺👏🏻

New releases are typically made shortly after new versions of [SQLite](https://www.sqlite.org) are released.

**Comment by m4heshd** [comment] 2021-07-25 18:04
> thanks for mentioning the SQLite3 Multiple Ciphers project.

Of course. Your project deserves all the attention and glory as much as how valuable and useful it is. 

> BTW, feedback like yours frequently lead to improvements of the project.

Glad to be in any value to your work.

> New releases are typically made shortly after new versions of SQLite are released.

I noticed that since I'm subscribed to your release notifications. It's really good news since `better-sqlite3` does the same. Hoping to keep a good schedule on my end too. 🤞🏻

**Closed** 2021-09-10 21:24 UTC
