### ISSUE TITLE
Support for AEGIS cipher?

### ISSUE THREAD

**Issue by ethindp** [utelle/SQLite3MultipleCiphers#182] opened 2024-11-26 06:10 UTC
It would be pretty nice if support for the AEGIS cipher was added. The reference implementation is in Zig, but there are other extremely fast implementations in both C and C++ (see [here](https://github.com/cfrg/draft-irtf-cfrg-aegis-aead?tab=readme-ov-file#known-implementations)). This cipher is most likely the currently known fastest cipher other than hardware-enabled AES, according to it's specification and benchmarks. This makes it seem like a prime candidate for something like SQLite3MC, so I thought I'd bring it up since it would be pretty neat to see it included.

**Comment by utelle** [comment] 2024-11-26 16:47
> It would be pretty nice if support for the AEGIS cipher was added. The reference implementation is in Zig, but there are other extremely fast implementations in both C and C++ (see [here](https://github.com/cfrg/draft-irtf-cfrg-aegis-aead?tab=readme-ov-file#known-implementations)).

AEGIS is certainly a good candidate for being used in a cipher scheme. The [libaegis](https://github.com/aegis-aead/libaegis) C implementation seems to be the one best suited for integration. However, I will have to check what needs to be done to make it operational when integrated in the source code amalgamation.

Additionally, I will have to decide which key derivation method should be used.

> This cipher is most likely the currently known fastest cipher other than hardware-enabled AES, according to it's specification and benchmarks. This makes it seem like a prime candidate for something like SQLite3MC, so I thought I'd bring it up since it would be pretty neat to see it included.

Yes, AEGIS seems to be very performant, if AES hardware support is available (as is the case on most modern processors). Although it is not (yet) standardized, it is obviously adopted broadly. So, yes, I will consider to add a cipher scheme based on AEGIS. However, I can't promise any release date yet.

**Comment by utelle** [comment] 2024-11-26 17:05
> That's alright. Yeah, libaegis looks like a very nice implementation. From my digging into the code, I don't know how you'd amalgamate it properly (but obviously it's possible)

For being usuable for the amalgamation the code will need some adjustments to avoid potential symbol name clashes. (Unfortunately, C doesn't support namespaces like C++.)

> As for KDF, well, there's Argon2 if you want to add that in.

Yes, I consider to use _Argon2_ for this purpose. Again, I need to find a suitable C implementation with a compatible license that can be integrated with reasonable effort.

**Comment by utelle** [comment] 2024-11-28 15:40
> > That's alright. Yeah, libaegis looks like a very nice implementation.

In principle, yes. It is by far the cleanest implementation.

> From my digging into the code, I don't know how you'd amalgamate it properly (but obviously it's possible)

No, unfortunately it is **not** _obviously possible_.

In the meantime I took a closer look at the implementation. The source code in its current form is absolutely not suited for amalgamation. The same names for static structures, types and preprocessor symbols are used all over the place in the various implementations resulting in tons of name clashes. No problem, if the source files are compiled separately. But impossible to compile successfully as amalgamated source code.

Of course, it is not impossible to restructure and/or rewrite the source to avoid the problems. But it is a lot of work.

**Comment by utelle** [comment] 2024-11-28 15:40
> > That's alright. Yeah, libaegis looks like a very nice implementation.

In principle, yes. It is by far the cleanest implementation.

> From my digging into the code, I don't know how you'd amalgamate it properly (but obviously it's possible)

No, unfortunately it is **not** _obviously possible_.

In the meantime I took a closer look at the implementation. The source code in its current form is absolutely not suited for amalgamation. The same names for static structures, types and preprocessor symbols are used all over the place in the various implementations resulting in tons of name clashes. No problem, if the source files are compiled separately. But impossible to compile successfully as amalgamated source code.

Of course, it is not impossible to restructure and/or rewrite the source to avoid the problems. But it is a lot of work.

**Comment by ethindp** [comment] 2024-11-28 18:18
I didn't know those difficulties existed... Maybe some of the other implementations would work?

**Comment by utelle** [comment] 2024-11-28 19:50
> I didn't know those difficulties existed...

Well, that's not very surprising. This can be found out only by closely inspecting the implementation.

> Maybe some of the other implementations would work?

No, I checked all C implementations mentioned in [draft-irtf-cfrg-aegis-aead](https://github.com/cfrg/draft-irtf-cfrg-aegis-aead). Except for `libaegis` they are either incomplete, not well maintained or not in good shape.

IMHO `libaegis` is the best option. But it will take time to adapt the source code.

**Comment by utelle** [comment] 2024-12-04 22:57
I made some progress with adapting the `libaegis` code to make it suitable for amalgamation. However, I still have to make some tests to verify that the code _"survived"_ all the necessary modifications.

`libaegis` includes support for 6 AEGIS variants: `aegis-128l`, `aegis-128x2`, `aegis-128x4`, `aegis-256`, `aegis-256x2`, and `aegis-256x4`. It has to be decided, which variant(s) should be selectable in _SQLite3MC_ and which variant should be the default.

**Comment by ethindp** [comment] 2024-12-04 23:01
Is there some way we can do auto-detection here? Like based on CPU features? (Though given non-x86/x64 architectures may not possess run-time CPU identification instructions that may be harder to do than I think...) I suspect that opting for the 256-bit variants would be the safest bet to start with as the default, and then allowing people to select different variants can be added thereafter. So if we stick to 256-bit security we are limited to 256x2/256x4/256. I think that x2/x4 is for AVX or vectorized implementations but 256 is not necessarily vectorized (but I could be wrong here).

**Comment by utelle** [comment] 2024-12-04 23:26
> Is there some way we can do auto-detection here? Like based on CPU features?

In principle, it would be possible to inspect CPU features. However, SQLite databases should be compatible, independent of the hardware the library runs on. Therefore, a deterministic choice should be preferred. That is, exactly **one** default variant (and other variants optionally selectable).

> (Though given non-x86/x64 architectures may not possess run-time CPU identification instructions that may be harder to do than I think...)

The current `libaegis` code selects the _best_ implementation for each variant based on CPU features. However, I think the implementation is suboptimal, because for applications compiled in 32-bit mode always the implementation without hardware support is selected.

> I suspect that opting for the 256-bit variants would be the safest bet to start with as the default,

Yes, with respect to security one of the 256-bit variants is most likely the preferred default.

> So if we stick to 256-bit security we are limited to 256x2/256x4/256. I think that x2/x4 is for AVX or vectorized implementations but 256 is not necessarily vectorized (but I could be wrong here).

Well, the variants `aegis-256`, `aegis-256x2`, and `aegis-256x4` are all available for all environments, with or without AES hardware support, with or without AVX2 / AVX512 support and so on. The `x2` and `x4` variants, however, profit from the availability of special AES instructions. 

All variants result in different encryptions for the same clear-text message. That is, a variant has to be selected explicitly by the user.

**Comment by Qriist** [comment] 2024-12-04 23:57
> `libaegis` includes support for 6 AEGIS variants: `aegis-128l`, `aegis-128x2`, `aegis-128x4`, `aegis-256`, `aegis-256x2`, and `aegis-256x4`. It has to be decided, which variant(s) should be selectable in _SQLite3MC_ and which variant should be the default.
> Is there some way we can do auto-detection here? Like based on CPU features? (Though given non-x86/x64 architectures may not possess run-time CPU identification instructions that may be harder to do than I think...)
> Well, the variants `aegis-256`, `aegis-256x2`, and `aegis-256x4` are all available for all environments
> All variants result in different encryptions for the same clear-text message. That is, a variant has to be selected explicitly by the user.

It's not clear to me if the more advanced versions use all features in tandem, or if it selects an available mode of processing under the hood based on internal preference. It's something that's hard to test without having a bunch of computers with known different capabilities laying around. 

Additionally, this: `(software, AVX512, VAES + AVX2, AES-NI, ARM Crypto)` suggests that the library can process the `256x4` via 5 different configuration routes.

Based on a modicum of research, it appears `AES-NI` and `AVX2` have been universally around in desktop CPUs for about 15 years while `VAES` has been mostly in high-end/server computers for about 5. 

Since all schemes return different data but all are available regardless of enviornment (meaning data is never inaccesible in suboptimal defaults), and all claim support for `AES-NI`, I think I would suggest `aegis-256x2` as a reliable default. Naturally, the other 5 should be manually selectable.

**Comment by utelle** [comment] 2024-12-05 10:39
> > In 32-bit mode always the AES software implementation is chosen.
> 
> I'm curious if that's true generally or if it is a bug on your own specific system. I'd interested in helping to test that. I'm actually also curious how many people still use 32-bit systems.

I use Visual C++ 2022, and if I compile for 32-bit then the preprocessor instructions in the `libaegis` code disable all configurations except for the AES software configuration. If this is a bug then it is already in the original code.

I will look into this and check whether I can manage to enable AES-NI support in 32-bit mode.

> > IMHO we should try to benchmark the various configurations and then select the default based on the results.
> 
> Well, I can agree with that in principle. The thing is, I expect the 128 family will be drastically faster in all categories than the given 256 counterpart.

Yes, in general the 128 variants will be faster than the 256 variants. However, it will depend on the available processor how big the differences are.

With respect to security a 256 variant should be preferred. That is, the 128 variants will be optional to choose from, but the default will be one of 256, 256x2, or 256x4. In principle, we could choose a different default depending on 32-bit or 64-bit mode, but IMHO that would be rather confusing for the users of the library.

> When you factor in the different hardware modes that may be available in different types of systems with different types of resources, the numbers would probably be so scattershot that it'd be hard to infer anything useful. It's sort of why I suggested just going with the most advanced version and allowing the auto-detection to kick in.

What I'd like to get a feeling for is how _soft_ configuration compares to _AES-NI_, _AVX2_, and _AVX512_. That is, how big is the penalty, if AES hardware support is not enabled.

> That said.. My CPU is a mid-grade model that's about 4 years old. [...] Of those hardware modes you listed, it looks like AVX2 is my most recent supported option.

_AVX2_ is probably supported by all recent x86 processors. So, choosing 256x2 or 256x4 as the default is most likely a reasonable decision.

> If you prepare a beta dll/source then I'd be happy to provide what benchmarks I can. I'll even try the modes I don't have just to report what happens.

I consider to make my `libaegis` modifications available in a separate repository. Integrating `libaegis` into `SQLite3MC` will still take a considerable amount of time. I'll drop a note when sources are available for further testing.

**Comment by jedisct1** [comment] 2024-12-05 17:20
Hi!

I'd suggest 128X2 and maybe 128X4. 

128X2 is faster than 128L on most modern CPUs, including ARM CPUs. 

128X4 is extremely fast on CPUs with AVX512 extensions, but is mostly useful for large inputs. I don't know how relevant that is to this project. 

Thanks to the large nonce size (compared to 96 bits) and the high usage limits, the 256 bit variants are usually not necessary, even against multi-target attacks.

**Comment by jedisct1** [comment] 2024-12-05 17:35
AES-NI can certainly be enabled on Win32. It's not enabled in libaegis just to be safe, since I don't have a Windows system to test this on.

**Comment by ethindp** [comment] 2024-12-05 18:57
I'd avoid AVX-512 unless we really need it, just because from what I remember Intel has removed that from most more "modern" processors. Mine possesses it but it's a Tigerlake 11th-generation processor, but I don't think the 12th-generation ones or beyond has it other than in server environments.

**Comment by utelle** [comment] 2024-12-05 20:16
> I'd suggest 128X2 and maybe 128X4.

At the moment I intend to make the `AEGIS` cipher available in _SQLite3MC_ in all variants: `128L`, `128x2`, `128x4`, `256`, `256x2`, and `256x4` - unless I find out that adding them all is too cumbersome to implement.

> 128X2 is faster than 128L on most modern CPUs, including ARM CPUs.
> 128X4 is extremely fast on CPUs with AVX512 extensions, but is mostly useful for large inputs. I don't know how relevant that is to this project.

The maximal page size of SQLite databases is 64 kB, with a default of 4 kB. However, many people deal with really large SQLite databases, where speed will matter.

> Thanks to the large nonce size (compared to 96 bits) and the high usage limits, the 256 bit variants are usually not necessary, even against multi-target attacks.

I'm still undecided which variant to choose as the default. And actually, a decision is not needed until a release with AEGIS support will be made.

> AES-NI can certainly be enabled on Win32. It's not enabled in libaegis just to be safe, since I don't have a Windows system to test this on.

It is definitely a bit strange that AES-NI is disabled in 32-bit in `libaegis`. As said I will look into this issue and will try to adjust the preprocessor instructions.

**Comment by utelle** [comment] 2024-12-05 20:18
> I'd avoid AVX-512 unless we really need it, just because from what I remember Intel has removed that from most more "modern" processors. Mine possesses it but it's a Tigerlake 11th-generation processor, but I don't think the 12th-generation ones or beyond has it other than in server environments.

IMHO this is a non-issue. Even if we made `128x4` or `256x4` the default, at runtime the implementation would be chosen based on the available CPU features.

**Comment by Qriist** [comment] 2024-12-05 23:06
> It is definitely a bit strange that AES-NI is disabled in 32-bit in `libaegis`. As said I will look into this issue and will try to adjust the preprocessor instructions.

I opened a github issue since there were no indications that they were aware of the bug.
https://github.com/aegis-aead/libaegis/issues/13#issue-2721629591

**Comment by jedisct1** [comment] 2024-12-05 23:17
> > It is definitely a bit strange that AES-NI is disabled in 32-bit in `libaegis`. As said I will look into this issue and will try to adjust the preprocessor instructions.
> 
> I opened a github issue since there were no indications that they were aware of the bug. [aegis-aead/libaegis#13 (comment)](https://github.com/aegis-aead/libaegis/issues/13#issue-2721629591)

https://github.com/utelle/SQLite3MultipleCiphers/issues/182#issuecomment-2521019539 🤣

**Comment by Qriist** [comment] 2024-12-05 23:19
> [#182 (comment)](https://github.com/utelle/SQLite3MultipleCiphers/issues/182#issuecomment-2521019539) 🤣

Whoops, missed that you're the dev for libaegis. Apologies!

**Comment by utelle** [comment] 2024-12-05 23:34
> AES-NI can certainly be enabled on Win32. It's not enabled in libaegis just to be safe, since I don't have a Windows system to test this on.

In the meantime I simply enabled AES-NI for the 32-bit build. Under Windows 11 compiled with Visual C++ 2022 in 32-bit mode it worked flawlessly for all AEGIS configurations ( soft, AES-NI, AVX2, AVX512).

I verified that all variants in all configurations of the modified library return the same results as the original library for my small test case.

I will test under Linux with GCC within the next couple of days.

Unfortunately I don't have access to ARM/ARM64 and PowerPC systems, that is, I can't test those platforms.

**Comment by utelle** [comment] 2024-12-07 09:05
@jedisct1 I started to adopt the latest [libaegis](https://github.com/aegis-aead/libaegis/commits/main/) changes regarding the MAC API. Is there a reason why the new MAC API is not (yet) implemented for `128x4`, `256x2` and `256x4`? Or will they be adjusted to the new API, too?

**Comment by jedisct1** [comment] 2024-12-07 09:14
> @jedisct1 I started to adopt the latest [libaegis](https://github.com/aegis-aead/libaegis/commits/main/) changes regarding the MAC API. Is there a reason why the new MAC API is not (yet) implemented for `128x4`, `256x2` and `256x4`? Or will they be adjusted to the new API, too?

It's just that I didn't had time to update the remaining variants. They will be adjusted to the new API and construction. Having a dedicated type is a bit cleaner; in particular, it ensures that the input message remains empty.

**Comment by utelle** [comment] 2024-12-07 11:32
> It's just that I didn't had time to update the remaining variants. They will be adjusted to the new API and construction.

Ok. Good to know. It is quite a laborious task...

> Having a dedicated type is a bit cleaner; in particular, it ensures that the input message remains empty.

Yes, indeed. The API is cleaner.

**Comment by utelle** [comment] 2024-12-09 16:46
@jedisct1 I forked your repository [aegis-aead/libaegis](https://github.com/aegis-aead/libaegis) and created a separate branch [`amalgamation`](https://github.com/utelle/libaegis). 

For _SQLite3MC_ I need to be able to compile `libaegis` as part of the amalgamated source code. This required to introduce unique function names for the internal functions of all _AEGIS_ variants. Additionally, I prefixed almost all C preprocessor symbols with `AEGIS_` to avoid possible symbol name clashes. All basic AES block related functions (`xor`, `and` ...) are now inline functions (instead of partially preprocessor macros).

I also adjusted the GitHub workflows to allow testing the amalgamated implementation. The CI workflow run works already.

Regarding the functions `aegis???_mac_init` I have a question: For some variants the `mac_state` structure is initialized via `memset`, for some not. Should a call to `memset` be added for those variants, where it is missing? Or should the call to `memset` be removed for **all** variants?

**Comment by jedisct1** [comment] 2024-12-09 16:56
`master` is a development branch. The MAC API and construction changes are still a work in progress, since the AEGISMAC construction hasn't even been merged to the specification yet (this is going to happen in the next few days).

You can stick to the `0.2.1` release tag. But the MAC APIs shouldn't be needed to SQLite3MultipleCiphers, so you can also safely remove these functions.

**Comment by jedisct1** [comment] 2024-12-09 16:59
You can also probably remove all the `aegis*_state_*` functions if you don't need streaming.

**Comment by utelle** [comment] 2024-12-09 17:27
> `master` is a development branch.

I'm aware of the fact that `main` is a development branch. 😄 

> The MAC API and construction changes are still a work in progress, since the AEGISMAC construction hasn't even been merged to the specification yet (this is going to happen in the next few days).

I'm not in a hurry, because there will be quite some work to implement the `SQLite3MC` side of an _AEGIS_ based cipher scheme.

I will try to keep up with the development in [aegis-aead/libaegis](https://github.com/aegis-aead/libaegis).

> You can stick to the `0.2.1` release tag. But the MAC APIs shouldn't be needed for SQLite3MultipleCiphers, so you can also safely remove these functions.

Most likely, I will need only the functions `aegis???_encrypt_detached` and `aegis???_decrypt_detached` for `SQLite3MC`. Additionally, I will need a _special_ version of `aegis???_decrypt_detached` that does not clear the output buffer; this will allow trying to recover a corrupted database.

BTW, is it possible to use the same buffer for input and output of the functions `aegis???_encrypt_detached` and `aegis???_decrypt_detached` , so that a message can be encrypted resp decrypted in-place?

> You can also probably remove all the `aegis*_state_*` functions if you don't need streaming.

Yes, most likely I could remove big parts of the library for my use case.

**Comment by utelle** [comment] 2024-12-13 22:58
Short update: I'm making good progress with implementing an AEGIS-based cipher scheme in _SQLite3 Multiple Ciphers_.

However, one aspect needs to be discussed: For the cipher schemes `chacha20` and `ascon128` one-time-keys are used for page encryption. These one-time keys are derived from the main key (which is derived from the passphrase given by the user), some nonce and the page number.

My first impulse was to use this one-time key approach for the `aegis` cipher as well. However, from the AEGIS documentation I learned that AEGIS MACs should not be used as hashes. That imposes the question, how the one-time keys should be derived. I could use one of the implementations from `chacha20` or `ascon128`. But which one? Or should I just use the main key, and some nonce directly with the `aegis` algorithm? Or is there a way to do it with AEGIS functions?

Opinions?

**Comment by jedisct1** [comment] 2024-12-14 00:34
The nonce doesn't have to be secret. You can use the page number as the nonce directly, or as a part of the nonce.

Since nonces are at least 128 bits, you can reserve 64 bits (or even less) for the page number, and use the rest as a per-database random identifier.

**Comment by utelle** [comment] 2024-12-14 11:30
> The nonce doesn't have to be secret. You can use the page number as the nonce directly, or as a part of the nonce.

The nonce will be saved in reserved space on each database page (depending on the selected AEGIS variant 128 or 256 bits). A new nonce will be generated each time a database page is written to the database file.

> Since nonces are at least 128 bits, you can reserve 64 bits (or even less) for the page number, and use the rest as a per-database random identifier.

For several ciphers currently supported by _SQLite3 Multiple Ciphers_ the encryption process is as follows:

1. Derive a main key from the passphrase entered by the user and a random salt (which is stored in the database header). That is: `key_main = f(passphrase, salt)`. In case of _AEGIS_ _Argon2_ will be used for function `f`. The main key can be changed by the user by applying a `PRAGMA rekey` command.
2. Per page a new key is derived on each page write: `key_page = g(key_main,nonce,page_no)`. Function `g` is implemented based on a `ChaCha20` resp `Ascon128` hash.

The question is how to proceed in step (2) for the _AEGIS_ based cipher.

**Comment by jedisct1** [comment] 2024-12-14 14:56
With AEGIS-256*, you definitely don't need to do that.

Use `160_random_bits || page_nr || 0*`  (or pad with something else such as a database-specific key, the major version number, etc) as the nonce. Collisions won't happen, even if the same page kept being updated.

With AEGIS-128*, you may be concerned about the same block being updated more than 2^64 times (which still represents at least 77919046967 terabytes to store with the smallest page size), or more than 2^48 times (about 1.2 exabytes, with the smallest page size) to stay within NIST recommendations.

If you really want to derive a new key for every block, you can use the libaegis `stream()` function for that. AEGIS-128L is enough, as the output size will be too short to take advantage of other 128 variants.

By the way, ChaChaPoly is not safe to use with keys derived from low-entropy material such as passwords due to [partitioning oracle attacks](https://eprint.iacr.org/2020/1491.pdf]).
Also, using the output of Argon2 directly prevents the password from being changed, which is sad. On database creation, you'd better create a random key, and XOR it with the Argon2 output in order to encrypt it.

**Comment by utelle** [comment] 2024-12-14 16:50
> With AEGIS-256*, you definitely don't need to do that.
> 
> Use `160_random_bits || page_nr || 0*` (or pad with something else such as a database-specific key, the major version number, etc) as the nonce. Collisions won't happen, even if the same page kept being updated.

Ok. That is, with this approach page encryption would use the main key (as derived in step (1)) and a 256 bits nonce (created as described above).

> With AEGIS-128*, you may be concerned about the same block being updated more than 2^64 times (which still represents at least 77919046967 terabytes to store with the smallest page size), or more than 2^48 times (about 1.2 exabytes, with the smallest page size) to stay within NIST recommendations.

I think this is an academic limitation not relevant in real-world applications.

> If you really want to derive a new key for every block, you can use the libaegis `stream()` function for that. AEGIS-128L is enough, as the output size will be too short to take advantage of other 128 variants.

I'd like to ensure a reasonable level of security. If new keys per database page + nonce don't increase security compared to using the main key + nonce for all pages, then deriving new keys would not make sense.

> By the way, ChaChaPoly is not safe to use with keys derived from low-entropy material such as passwords due to [partitioning oracle attacks](https://eprint.iacr.org/2020/1491.pdf%5D).

Thanks for the link!

Currently, most cipher schemes supported by _SQLite3 Multiple Ciphers_ use a PBKDF2 algorithm with SHA256 to derive a key from a passphrase. The passphrase could be anything: a simple password or a long random byte sequence - it's up to the user.

Security will be relative. If a user provides passphrases like `123456` protection against database manipulation will be low.

> Also, using the output of Argon2 directly prevents the password from being changed, which is sad.

I intend to use the function `argon2id_hash` from the _Argon2_ reference implementation to derive the main key from the given passphrase. Why the passphrase can't be changed? (In practise, changing the passphrase of the database will work by decrypting with the key derived from the old passphrase and then encrypting with the key derived from the new passphrase.)

> On database creation, you'd better create a random key, and XOR it with the Argon2 output in order to encrypt it.

The problem is that such a random key has to be preserved somewhere, so that the database can be decrypted at a later time. However, the space in a SQLite database that can be used for this purpose is limited. Currently, a 16 byte salt is stored in the database header - and that's it.

I thought that using the hash resulting from `argon2id_hash(passphrase, salt, .Argon2 config parameters...)` as the main key is good enough.

**Comment by ethindp** [comment] 2024-12-14 17:26
> I thought that using the hash resulting from argon2id_hash(passphrase, salt, .Argon2 config parameters...) as the main key is good enough.

I thought too that this was enough -- before I just switched to the built-in ciphers this was what I did for key derivation. I'd love to learn more as to why this is a problem -- I assumed argon2 could be used as a reliable KDF.

**Comment by utelle** [comment] 2024-12-15 23:10
I did some research about _Argon2_, and all sources I checked so far told me that the output from `Argon2_hash` can be used as a derived key or as a password hash. Therefore I implemented the KDF for the new _Aegis_ cipher scheme in that way. (If there are good reasons to do it differently, please let me know and point me to relevant sources.)

Regarding the page encryption I use for now `aegis_stream` for deriving page key and page nonce from the main key, but I'm open to discuss whether this extra step should be done or not. The alternative would be to use the main key for all pages and to construct the nonce like proposed by @jedisct1 (that is, `160_random_bits || page_nr || 0*`) or just `256_random_bits` or something inbetween.  

In my development environment the new cipher scheme seems to work already properly. Therefore I will make the `aegis` cipher scheme available for testing in a separate branch soon.

**Comment by utelle** [comment] 2024-12-17 08:35
I added a first version of the _AEGIS_ cipher scheme in branch [aegis](https://github.com/utelle/SQLite3MultipleCiphers/tree/aegis). Please give it a try and report any issues. TIA.

**Comment by utelle** [comment] 2024-12-18 13:24
In the meantime I struggled a bit with the amalgamation procedure, because the current amalgamation script doesn't support to force certain headers to be reincluded (a feature required for amalgamating the _AEGIS_ source code). Locally I use now a different tool. Not sure yet, how to handle amalgamation in the future.

After some minor adjustments the GitHub CI runs now succeed. However, that is not the whole truth, unfortunately. I tested cross-compiling for various platforms. Currently, compiling for **ARM 32-bit** fails - I have to investigate what is causing the problem. 

And compiling for **PowerPC64** also fails with the error message `pragma GCC target("+altivec+crypto") is invalid` (and many subsequent errors). I have no idea what's wrong with that pragma. @jedisct1 Any ideas?

**Comment by jedisct1** [comment] 2024-12-19 11:35
Compilation to PPC was only tried to Zig, but the current version should make it compatible with gcc and old versions of clang.

**Comment by utelle** [comment] 2024-12-19 20:29
> > Currently, compiling for ARM 32-bit fails - I have to investigate what is causing the problem.

I managed to compile for ARM 32-bit with Visual C++.

> Compilation to PPC was only tried to Zig, but the current version should make it compatible with gcc and old versions of clang.

Thanks for the adjustments. Cross-compiling now works.

However, I have now another issue with cross-compiling for **Android**. The header file `#include <cpu-features.h>` is not found. Used target was `android-21`.

**Comment by jedisct1** [comment] 2024-12-19 22:51
You may need to add `/opt/android-ndk/sources/android/cpufeatures` to the include paths.

**Comment by utelle** [comment] 2024-12-21 10:06
@ethindp Did you have the chance to test the new AEGIS cipher scheme?

According to the [SQLite draft release log](https://www.sqlite.org/draft/releaselog/3_48_0.html) the next release of SQLite is about to happen in early January 2025. At the moment I tend to exclude the _AEGIS_ cipher scheme from the next release of _SQLite3 Multiple Ciphers_ due to a lack of experiences with the new cipher scheme.

**Comment by ethindp** [comment] 2024-12-21 12:34
I haven't yet, will definitely give it a go assuming I can build an amalgamation of it (the project where I use SQLite3MC uses the amalgamation). Will let you know my results!

**Comment by ethindp** [comment] 2024-12-21 12:51
Okay, so I just tried amalgamating it and it isn't building for me, says that it can't find aegis128l.h. Looking at the errors, there are lines like:

```c
#include "aegis128l.h"
```

Scattered throughout the code. I just ran the amalgamate.py script and not any of the patch ones, so maybe I did something wrong?

**Comment by utelle** [comment] 2024-12-21 13:28
> I haven't yet, will definitely give it a go assuming I can build an amalgamation of it (the project where I use SQLite3MC uses the amalgamation). Will let you know my results!

Unfortunately, the current Python script does not work, because it doesn't allow to specify headers to be included more than once - a feature required by the _AEGIS_ sources..

> I just ran the amalgamate.py script and not any of the patch ones, so maybe I did something wrong?

As I wrote in [this post](https://github.com/utelle/SQLite3MultipleCiphers/issues/182#issuecomment-2551316995) the amalgamation script doesn't work.

However, you can find the amalgamated source [here](https://github.com/utelle/SQLite3MultipleCiphers-cb/tree/sqlite3mc/sqlite3mc), where I tested cross-compilation for various platforms. Use the file [sqlite3.c](https://github.com/utelle/SQLite3MultipleCiphers-cb/blob/sqlite3mc/sqlite3mc/sqlite3.c).

**Comment by ethindp** [comment] 2024-12-21 13:31
Oh, okay, will use that, thank you! Will let you know if everything seems to work over here!

**Comment by ethindp** [comment] 2024-12-21 13:51
Well, I can confirm that it appears to work just fine with my test code. Am not suffering any read errors or anything else.

**Comment by utelle** [comment] 2024-12-21 14:15
> Well, I can confirm that it appears to work just fine with my test code. Am not suffering any read errors or anything else.

Good to hear. Nevertheless, there are still some open points:

1. Determine the default cipher parameters, that is, the _Argon2_ configuration (at the moment `tcost=2, mcost=19MB, pcost=1` (where `tcost` is the number of iterations, `mcost` the amount of memory to be used, and `pcost` the number of parallel threads). I found these values [here](https://en.wikipedia.org/wiki/Argon2) under the heading _Recommended minimum parameters_. However, people tend to use the defaults, and therefore it should be checked whether those values are sufficient or maybe too low.
2. Perform more thorough tests
3. Fix the amalgamation script (or find an alternative)

**Comment by ethindp** [comment] 2024-12-21 14:33
For the argon2 stuff, why not just use the params from OWASP? You definitely don't want the parameters too high, particularly on mobile; iOS for example restricts things like that to about 47 MB, and any higher will either result in weird behavior or errors. I think the best security would be m=47104, t=1, p=1, if using anything but argon2i, or m=7168, t=5, p=1 otherwise. All of the five parameter tuples offer an identical level of defense. The unfortunate thing, if I understand argon2 correctly, is that we cannot dynamically select these parameters because they result in different hashes. If we could, I would recommend selecting them based on system characteristics, but...

**Comment by ethindp** [comment] 2024-12-21 15:14
I'm not 100-percent certain about the params; I'm no expert or anything. But the OWASP defaults seem reasonable to me while also being secure.

Re: the unused code. I say leave it in. Does it make the resulting binaries a bit larger? I mean sure, assuming the optimizer doesn't just remove them since they're unused. I think the cost is something people can absorb, especially since you can remove unused ciphers.

**Comment by utelle** [comment] 2024-12-21 16:16
> I'm not 100-percent certain about the params; I'm no expert or anything. But the OWASP defaults seem reasonable to me while also being secure.

I consider to increase the number of iterations to 3 or 4. But I will measure the time it takes to generate the key material.

> Re: the unused code. I say leave it in. Does it make the resulting binaries a bit larger? I mean sure, assuming the optimizer doesn't just remove them since they're unused. I think the cost is something people can absorb, especially since you can remove unused ciphers.

Adding the _AEGIS_ cipher scheme increases the total size of the binaries by about 15 percent. My guess is that removing unused functions from _AEGIS_ will bring it down to 10 percent at most - depending on how good the compiler is in optimizing. Probably not worth the effort.

And as you correctly point out, there are other measures to reduce code size, if necessary.

**Comment by utelle** [comment] 2024-12-24 10:56
The current state is now available in the repo.

The AEGIS code was cleaned up a bit. And the amalgamation script should now work again.

**Comment by utelle** [comment] 2024-12-27 08:06
I merged the _AEGIS_ code into the main branch and updated the documentation. An official release will follow - most likely in early January.

**Closed by utelle** 2024-12-27 08:06 UTC
